# Generated by Django 5.2.3 on 2025-07-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("images", models.ImageField(blank=True, null=True, upload_to="home/")),
                ("content", models.TextField()),
            ],
        ),
    ]
